### ISSUE TITLE
Selection of the panel decoder architecture.

### ISSUE THREAD

**Issue by chencchengh** [maria-korosteleva/Garment-Pattern-Estimation#2]
Hi, 

Your work is amazing and thank you for sharing the code and dataset.
I am curious about why do you select "LSTMDecoderModule" over other candidates (e.g., "MLPDecoder") as the panel decoder.
Can you share some insights about the performance difference or artifacts when using alternative decoders ?
It seems that this wasn't discussed in the paper, but alternative modules do exist in the code.

Thanks in advance.

**Comment by maria-korosteleva** [comment]
Hi! Thank you for your kind words and interest in our work!

We originally chose LSTM for our panel decoders, as the panels have a
natural sequential representation, and LSTMs allowed weight sharing and
flexibility with sequence length. When combined with the Loop Loss, the
panel predictions became high enough in quality, so we didn't have much
reason to change that part of the architecture.

We did some experiments with MLPDecoder to confirm our choice, but they
were done very roughly (e.g. smaller #of garment types in training
data). Unfortunately, it's been quite a while since we worked on them, so
the only number I could find right now is from an experiment where both
pattern and panel decoders were substituted with MLPs. Those were about
40-45 percentage points below our final model (60% vs 95% at the same stage
of training) on the number of panels and number of edges accuracies. We
decided not to invest further into clearing those experiments up, so they
didn't make it into the paper. I left it in the code for other curious
minds =)

If you ever decide to experiment with those modules, please, do let us know
the outcomes. That would be greatly appreciated



пт, 9 дек. 2022 г. в 20:05, chenghsiuchen ***@***.***>:

**Comment by chencchengh** [comment]
Thank you very much for your explanation !
